version: "3"

services:
  db:
    image: postgres:17.2
    container_name: ext.db
    environment:
      - POSTGRES_USER=ext_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ext
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -h db -lqt | grep -wo $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ext.network

networks:
  ext.network:

volumes:
  pgdata:
